spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.pldyuaelolozcrmyivrh&password=dPw0b8i6AQI148sU
spring.datasource.username=postgres
spring.datasource.password=dPw0b8i6AQI148sU

file.upload-dir=uploads/skenirani-dokumenti

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=true

springdoc.packagesToScan=com.example.backend
springdoc.swagger-ui.persist-authorization=true
springdoc.swagger-ui.disable-swagger-default-url=true
jwt.secret=k9#mP2@n@d8!xZ8&aR7*vTa^yU62s4#$fA2+bCD_dS9-fa1=hI8
jwt.expiration=86400000