spring.application.name=backend

spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?user=postgres.pldyuaelolozcrmyivrh&password=dPw0b8i6AQI148sU
spring.datasource.username=postgres
spring.datasource.password=dPw0b8i6AQI148sU

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect